### PR TITLE
Use a node version manager

### PR DESCRIPTION
**Pull request by 6**
- installs `n` for node version management
- installs `avn` for automatic node version switching based on `.node-version` file.

### CODE REVIEW

**Comment by 6** [comment]
@DanGodfrey @benjyblack @johnsintal any thoughts on this? I've personally found `nvm` to be super slow compared to `n`.

**Comment by benjyblack** [comment]
I've only ever used `nvm` before, never had any issues with speed. I'm open to `n` though! Think of all the keystrokes we'll save!

**Comment by DanGodfrey** [comment]
I am also indifferent. My only thought is that we should probably update a tonne of readmes.

**Comment by 6** [comment]
Alright I'll go ahead and merge this then and update readmes

**Pull request merged**
